#       TheTime
#  Author: Joshua Wirtz
#  
#  The default TimeSystem will be default, it is called when the command is executed with no parameters.
#  
Time-Systems:
  default:
    second:
      ticksPerSecond: 20
    minute:
      secondsPerMinute: 60
    hour:
      minutesPerHour: 60
    day:
      hoursPerDay: 24
      dayNames:
        '1':
          name: Dies solis
        '2':
          name: Dies lunae
        '3':
          name: Dies martis
        '4':
          name: Dies mercurii
        '5':
          name: Dies lovis
        '6':
          name: Dies veneris
        '7':
          name: Dies saturni
    week:
      daysPerWeek: 7
    month:
      daysPerMonth:
        '1':
          name: MARTIUS
          days: 31
        '2':
          name: APRILIS
          days: 30
        '3':
          name: MAIUS
          days: 31
        '4':
          name: IUNIUS
          days: 30
        '5':
          name: QUINTILIS
          days: 31
        '6':
          name: SEXTILIS
          days: 31
        '7':
          name: SEPTEMBER
          days: 31
        '8':
          name: OCTOBER
          days: 31
        '9':
          name: NOVEMBER
          days: 30
        '10':
          name: DECEMBER
          days: 31
        '11':
          name: IANUARIUS
          days: 31
        '12':
          name: FEBRUARIUS
          days: 28
    year:
      zero: -753
      monthsPerYear: 12
    era:
      eras:
        '1':
          name: Rome is founded
          startYear: -753
          endYear: -510
        '2':
          name: Rome becomes a Republic
          startYear: -509
          endYear: -219
        '3':
          name: Hannibal invades Italy
          startYear: -218
          endYear: -46
        '4':
          name: Julius Caesar the first dictator
          startYear: -45
          endYear: -45